appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: B4klFe9QfIP8S6vlKhVJo0WvGhWIzG2AGUsVyYtp3wR0y6AtNIzRT5YEagP1ViEG5bP6ioBSwevJj4Pz/pnzPWrccMC07KKQqhXq2Hj9MBzIKAiQAz0QUPu0WcPYN7t1qwI50UMRJQIRU9f/236hf6ubsw6d2zHVwMDpJdyHCrBf19uNJNUQk5yMgLy2A0ueyuhcE0ckZ002aXxY8pXE90RMS04sZuuktIxzYt0RTQUsZ4VmTE2cvq5o8NZkcBKK997ci9YrkU1je1fbwnORm9+OeC1UmzYBxYqaeVW8yLyZ9XnW9oVdxm36REIJlF99mfKNe+IC5u+RAYT4jvfuw10IHIDMscOp0noGxlfg1F6Lj1+Tet4pr/zZ98aTuaL8tgeGdVQbfb/KhUe9d9khCP8Kw255l2Pu2UvXhPTTn2hDUXQ01/wZU/ehlRK35Axmon6OnvrKAWMMUCU0UikoqZMctz0cbv23BGPXsLE2nBaAJMOcfRozbOKYN6AehD5STVC4UXBnSli4+m8Ezhb+lBzNUbN0DNh9E9Et+DVV+jLrH7iL2qRZiWndfGxipMsngH9pC/LeAvxV8c6Q7kcasFwMu1weWDe3ml6iBtmSIIek9tvLEBfBuQnyXe5/l1OM5Cp56zmbkeCwlAcL5OcWs6Cg4J9zpVi3/jMuONRtoWM=}
provider:
  win: None
  linux: circle
  osx: None
  linux_ppc64le: None
  linux_aarch64: None
github:
  user_or_org: bahaelaila7
channels:
  sources:
  - bahaelaila7,conda-forge,anaconda,defaults
  targets:
  - bahaelaila7,main
